AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This provides the hosted zone and SSL certs for external Cumulus URLs.
Parameters:
  Domain:
    Type: String
    Default: smartcumulus.org

Resources:

  CumulusHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref Domain

# See README.md for notes about successfully deploying ACM certs
# Root and www should redirect to the prod dashboard domain
  AcmRootCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmWwwCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "www.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "www.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS


# Dashboard
  AcmDashCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "dashboard.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "dashboard.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmStagingDashCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "staging.dashboard.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "staging.dashboard.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmDevDashCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "dev.dashboard.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "dev.dashboard.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmAggCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "aggregator.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "aggregator.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmStagingAggCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "staging.aggregator.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "staging.aggregator.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmDevAggCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "dev.aggregator.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "dev.aggregator.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "api.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmStagingApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "staging.api.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "staging.api.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

  AcmDevApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "dev.api.${Domain}"
      DomainValidationOptions:
        - DomainName: !Sub "dev.api.${Domain}"
          HostedZoneId: !Ref CumulusHostedZone
      ValidationMethod: DNS

Outputs:
  RootCertificateArn:
    Description: "ACM Root Certificate ARN"
    Value: !Ref AcmRootCertificate

  WwwCertificateArn:
    Description: "ACM Www Certificate ARN"
    Value: !Ref AcmWwwCertificate

  DashCertificateArn:
    Description: "ACM Dashboard Certificate ARN"
    Value: !Ref AcmDashCertificate

  DashStagingCertificateArn:
    Description: "ACM Staging Dashboard Certificate ARN"
    Value: !Ref AcmStagingDashCertificate

  DashDevCertificateArn:
    Description: "ACM Dev Dashboard Certificate ARN"
    Value: !Ref AcmDevDashCertificate

  AggCertificateArn:
    Description: "ACM Aggregator Certificate ARN"
    Value: !Ref AcmAggCertificate

  AggStagingCertificateArn:
    Description: "ACM Staging Aggregator Certificate ARN"
    Value: !Ref AcmStagingAggCertificate

  AggDevCertificateArn:
    Description: "ACM Dev Aggregator Certificate ARN"
    Value: !Ref AcmDevAggCertificate

  ApiCertificateArn:
    Description: "ACM Aggregator Certificate ARN"
    Value: !Ref AcmApiCertificate

  ApiStagingCertificateArn:
    Description: "ACM Staging Aggregator Certificate ARN"
    Value: !Ref AcmStagingApiCertificate

  ApiDevCertificateArn:
    Description: "ACM Dev Aggregator Certificate ARN"
    Value: !Ref AcmDevApiCertificate

  CumulusHostedZoneId:
    Description: "Cumulus Hosted Zone ID"
    Value: !Ref CumulusHostedZone
