AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  SAM stack for Cumulus aggregator
Transform:
- AWS::Serverless-2016-10-31

# TODO: The global section is only meant for the dashboard API. We should split
# out the dashboard API into its own cloudformation template to limit this scope.

# Generally we are being lax w.r.t. CORS at the moment with the
# following items in mind:
# - The dashboard API is not wired up to a public URL
# - you can only access the private URL while on the BCH VPN
# - We want to be able to test from localhost in dev environment
# - When we are ready to move to staging/prod with this, we will add an API key
# - We may wire origins to a parameter populated per environment
Globals:
  Api:
    Cors:
      AllowMethods: "'GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  BucketNameParameter:
    Type: String
    Default: cumulus-aggregator-site-counts
  GlueNameParameter:
    Type: String
    Default: cumulus-aggregator
  AthenaWorkgroupNameParameter:
    Type: String
    Default: cumulus-aggregator
  DeployStage:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
  AggregatorDomainName:
    Type: String
  AggregatorCertArn:
    Type: String
  AggregatorHostedZoneID:
    Type: String


Resources:

### Lambda Functions

  # Data Processing

  FetchAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggFetchAuthorizer-${DeployStage}'
      Handler: src/handlers/site_upload/api_gateway_authorizer.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 100
      Description: Validates credentials before providing signed urls
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
          REGION: !Ref "AWS::Region"
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

  FetchUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggFetchUploadUrl-${DeployStage}'
      Handler: src/handlers/site_upload/fetch_upload_url.upload_url_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 100
      Description: Generates a presigned URL for uploading files to S3
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
          REGION: !Ref "AWS::Region"
      Events:
        SiteUploadAPI:
          Type: Api
          Properties:
            RestApiId: !Ref SiteApiGateway
            Path: /
            Method: POST
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

  ProcessUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggProcessUpload-${DeployStage}'
      Handler: src/handlers/site_upload/process_upload.process_upload_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 800
      Description: Handles initial relocation of upload data
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
          TOPIC_PROCESS_COUNTS_ARN: !Ref SNSTopicProcessCounts
          TOPIC_PROCESS_STUDY_META_ARN: !Ref SNSTopicProcessStudyMeta
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopicProcessCounts.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopicProcessStudyMeta.TopicName

  PowersetMergeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggPowersetMerge-${DeployStage}'
      Layers: [arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1]
      Handler: src/handlers/site_upload/powerset_merge.powerset_merge_handler
      Runtime: python3.9
      MemorySize: 4096
      Timeout: 800
      Description: Merges and aggregates powerset count data
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
      Events:
        ProcessUploadSNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopicProcessCounts
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

  StudyPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggStudyPeriod-${DeployStage}'
      Layers: [arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1]
      Handler: src/handlers/site_upload/study_period.study_period_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 800
      Description: Handles metadata outside of upload/processing for studies
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
      Events:
        ProcessUploadSNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopicProcessStudyMeta
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

  # Dashboard API

  DashboardGetChartDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggDashboardGetChartData-${DeployStage}'
      Layers: [arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1]
      Handler: src/handlers/dashboard/get_chart_data.chart_data_handler
      Runtime: python3.9
      MemorySize: 2048
      Timeout: 100
      Description: Retrieve data for chart display in Cumulus Dashboard
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
          GLUE_DB_NAME: !Sub '${GlueNameParameter}-${DeployStage}'
          WORKGROUP_NAME: !Sub '${AthenaWorkgroupNameParameter}-${DeployStage}'
      Events:
        GetChartDataAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /chart-data/{subscription_name}
            Method: GET
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AggregatorBucket
        - Statement:
          - Sid: GluePermissionsPolicy
            Effect: Allow
            Action:
              - glue:*Table*
              - glue:*Partition*
            Resource: 
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueNameParameter}-${DeployStage}'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${GlueNameParameter}-${DeployStage}/*'
        - Statement:
          - Sid: AthenaExecuteQueryPermissionsPolicy
            Effect: Allow
            Action:
              - athena:*
            Resource: !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaWorkgroupNameParameter}-${DeployStage}'

  DashboardGetMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggDashboardGetMetadata-${DeployStage}'
      Handler: src/handlers/dashboard/get_metadata.metadata_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 100
      Description: Retrieve data about site uploads
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
      Events:
        GetMetadataAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /metadata/
            Method: GET
        GetMetadataSiteAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /metadata/{site}/
            Method: GET
        GetMetadataSiteStudyAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /metadata/{site}/{study}
            Method: GET
        GetMetadataSiteStudySubscriptionAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /metadata/{site}/{study}/{subscription}
            Method: GET
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

  DashboardGetSubscriptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggDashboardGetSubscriptions-${DeployStage}'
      Layers: [arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1]
      Handler: src/handlers/dashboard/get_subscriptions.subscriptions_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 100
      Description: Retrieve data for chart display in Cumulus Dashboard
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
          GLUE_DB_NAME: !Sub '${GlueNameParameter}-${DeployStage}'
          WORKGROUP_NAME: !Sub '${AthenaWorkgroupNameParameter}-${DeployStage}'
      Events:
        GetSubscriptionsAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /subscriptions
            Method: GET
      # TODO: it :should: be possible to move these policies to a central role/policy
      # set that can be referenced in multiple places; see
      # https://stackoverflow.com/questions/64523817/aws-sam-multiple-functions-with-same-inline-policy
      # However - this causes a lot of nested policy conflicts that might require a
      # more comprehensive policy/role overhaul.
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AggregatorBucket
        - Statement:
          - Sid: GlueSubscriptionsPolicy
            Effect: Allow
            Action:
              - glue:*Table*
              - glue:*Partition*
            Resource: 
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueNameParameter}-${DeployStage}'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${GlueNameParameter}-${DeployStage}/*'
        - Statement:
          - Sid: AthenaSubscriptionsPolicy
            Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryResults
              - athena:GetWorkGroup
              - athena:GetQueryExecution
              - athena:StopQueryExecution
            Resource: !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaWorkgroupNameParameter}-${DeployStage}'

  DashboardGetStudyPeriodsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'CumulusAggDashboardStudyPeriods-${DeployStage}'
      Handler: src/handlers/dashboard/get_study_periods.study_periods_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 100
      Description: Retrieve data about the study period
      Environment:
        Variables:
          BUCKET_NAME: !Sub '${BucketNameParameter}-${DeployStage}'
      Events:
        GetStudyPeriodAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /study-periods/
            Method: GET
        GetStudyPeriodSiteAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /study-periods/{site}/
            Method: GET
        GetStudyPeriodSiteStudyAPI:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApiGateway
            Path: /study-periods/{site}/{study}
            Method: GET 
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${BucketNameParameter}-${DeployStage}'

### Lambda permissions

  ProcessUploadFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ProcessUploadFunction
      Principal: s3.amazonaws.com
      #This can't be a !Ref due to circular refs
      SourceArn: !Sub 'arn:aws:s3:::${BucketNameParameter}-${DeployStage}'
      SourceAccount: !Ref AWS::AccountId

### SNS topics
  SNSTopicProcessCounts:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'CumulusProcessCounts-${DeployStage}'
      Tags:
        - Key: Name
          Value: !Sub 'CumulusProcessCounts-${DeployStage}'

  SNSTopicProcessStudyMeta:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'CumulusProcessStudyMeta-${DeployStage}'
      Tags:
        - Key: Name
          Value: !Sub 'CumulusProcessStudyMeta-${DeployStage}'

### S3 Buckets

  AggregatorBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - ProcessUploadFunctionPermission
    Properties:
      BucketName: !Sub '${BucketNameParameter}-${DeployStage}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessUploadFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'site_upload/'

### Glue Resources

  GlueDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${GlueNameParameter}-${DeployStage}'
        Description: Database for serving data to Cumulus Dashboard

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${GlueNameParameter}-crawler-${DeployStage}'
      DatabaseName: !Ref GlueDB
      Role: !GetAtt CrawlerRole.Arn
      Configuration: "{\"Version\":1.0,\"Grouping\":{\"TableLevelConfiguration\":4}}"
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      Schedule:
        ScheduleExpression: "cron(0 22 ? * SUN *)"
      Targets:
        S3Targets:
          - Path: !Sub '${AggregatorBucket}/aggregates'

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${AthenaWorkgroupNameParameter}-${DeployStage}'
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: True
        PublishCloudWatchMetricsEnabled: True
        EngineVersion:
          SelectedEngineVersion: "Athena engine version 3"
        ResultConfiguration:
          OutputLocation: !Sub "s3://${BucketNameParameter}-${DeployStage}/athena/"

### IAM Roles 

  FetchAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole

  CrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
      Policies:
        - PolicyName: S3BucketAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${BucketNameParameter}-${DeployStage}/aggregates/*"


### API Gateways

# If you need to enable logging at the API Gateway level, uncomment the nodes 
# in this section. This should be left disabled for production since it is noisy
# and not useful for troubleshooting 95% of lambda issues.

  SiteApiGateway:
    Type: AWS::Serverless::Api
#    DependsOn: ApiCWLRoleArn 
    Properties:
      StageName: !Ref DeployStage
      Auth:
        Authorizers: 
          FetchAuth: 
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt FetchAuthorizerFunction.Arn
            Identity:
              Headers: [Authorization]
        DefaultAuthorizer: FetchAuth
      # If an external url is not required, delete/comment the Domain node
      Domain:
        DomainName: !Ref AggregatorDomainName
        CertificateArn: !Ref AggregatorCertArn
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref AggregatorHostedZoneID
        BasePath:
          - upload
      Name: !Sub "CumulusAggregatorSiteAPI-${DeployStage}"
#      MethodSettings:
#        - LoggingLevel: INFO
#          MetricsEnabled: True
#          DataTraceEnabled: True
#          ResourcePath: '/*' # allows for logging on any resource
#          HttpMethod: '*' # allows for logging on any method

### Cloudwatch Logging infra for API gateway

# The following ensures that logs generated by SiteAPIGateway will actually get
# to cloudwatch for the gateway

#  ApiCWLRoleArn:
#    Type: AWS::ApiGateway::Account
#    Properties: 
#      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

#  CloudWatchRole:
#      Type: AWS::IAM::Role
#      Properties:
#        AssumeRolePolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#            Action: 'sts:AssumeRole'
#            Effect: Allow
#            Principal:
#              Service: apigateway.amazonaws.com
#        Path: /
#        ManagedPolicyArns:
#          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'


  # TODO: we will add a gateway API key to this when the dashboard is ready
  # to handle it
  DashboardApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref DeployStage
      Name: !Sub "CumulusAggregatorDashboardApi-${DeployStage}"

Outputs:
  SiteWebEndpoint:
    Description: "Site API Gateway endpoint URL"
    Value: !Sub "https://${SiteApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${DeployStage}/"

  DashboardWebEndpoint:
    Description: "Dashboard API Gateway endpoint URL"
    Value: !Sub "https://${DashboardApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${DeployStage}/"
    