AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  SAM stack for Cumulus aggregator


Parameters:
  DeployStage:
    Type: String
    AllowedValues:
      - dev
      - test
      - regression
      - prod
  WAFArn:
    Type: String

Resources:
  SiteWebACLAssociation:
    Type: 'AWS::WAFv2::WebACLAssociation'
    Properties:
      WebACLArn: !Ref WAFArn
      ResourceArn: 
        Fn::Join:
          - ''
          - - 'arn:'
            - !Ref AWS::Partition
            - ':apigateway:'
            - !Ref AWS::Region
            - '::/restapis/'
            - Fn::ImportValue: !Sub "CumulusSiteApiProxy-${DeployStage}"
            - !Sub '/stages/${DeployStage}'

  DashboardWebACLAssociation:
    Type: 'AWS::WAFv2::WebACLAssociation'
    Properties:
      WebACLArn: !Ref WAFArn
      ResourceArn:
        Fn::Join:
          - ''
          - - 'arn:'
            - !Ref AWS::Partition
            - ':apigateway:'
            - !Ref AWS::Region
            - '::/restapis/'
            - Fn::ImportValue: !Sub "CumulusDashboardApiProxy-${DeployStage}"
            - !Sub '/stages/${DeployStage}'
