name: CI
on: [push]

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install linters
        #black is synced with the .pre-commit-hooks version
        run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0
      - name: Run black
        if: success() || failure() # still run black if above checks fails
        run: |
          black --check --verbose .