name: CI
on: [push]
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
      - name: Test with pytest
        run: |
          export AWS_DEFAULT_REGION=us-east-1; python -m pytest

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run ruff
        if: success() || failure() # still run black if above checks fails
        run: |
          ruff check
          ruff format --check
